_core:
  default_config_hash: yXadRE77Va-G6dxhd2kPYapAvbnSvTF6hO4oXiOEynI
langcode: es
uuid: 2c9b7e94-3254-47fc-8519-e265bf32022a
name: ObraNovaDigital
mail: corporativa_drupal@dev.com
slogan: ''
page:
  403: /node/2
  404: /node/1
  front: /user
admin_compact_mode: false
weight_select_max: 100
default_langcode: es
mail_notification: ''
